# Generated by Django 5.1 on 2025-08-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prefered_chanels', models.JSONField(default=list, help_text="Приоритет каналов: ['telegram', 'email', 'sms']")),
            ],
            options={
                'db_table': 'notification_user',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_chanels', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.user')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
