# Generated by Django 5.1 on 2025-08-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prefered_chanels',
            new_name='preferred_channels',
        ),
    ]
